// Bundles each site's own validation code (sites/<site>/lib/*.ts) into src/generated/, so the
// server validates content with exactly the code the site builds with, never a copy.
//
// - ajv and yaml are resolved from mcp/node_modules (the site's node_modules isn't installed
//   when this project builds); test/rules-deps.test.ts checks the versions match the site's.
// - A manifest records the git blob SHA of every site file that went into the bundle. The
//   server compares it with main before any write (src/guardrails/drift.ts).
import { build } from "esbuild";
import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";

const mcpRoot = path.resolve(import.meta.dirname, "..");
const repoRoot = path.resolve(mcpRoot, "..");
const outDir = path.join(mcpRoot, "src", "generated");

/** One entry per site with rules: the lib modules the server uses. */
const SITES = {
  "cura-aero": {
    root: "sites/cura.aero",
    modules: {
      rich: "lib/rich.ts",
      safeUrl: "lib/safe-url.ts",
      articles: "lib/articles.ts",
      landing: "lib/landing.ts",
      landingRoutes: "lib/landing-routes.ts",
    },
  },
};

export function gitBlobSha(content) {
  return createHash("sha1").update(`blob ${content.length}\0`).update(content).digest("hex");
}

/** Packages always come from mcp/node_modules, even when sites/<site>/node_modules exists locally. */
const resolvePackagesFromMcp = {
  name: "resolve-packages-from-mcp",
  setup(b) {
    b.onResolve({ filter: /^[^./]/ }, async (args) => {
      if (args.pluginData?.fromMcp) return undefined;
      const resolved = await b.resolve(args.path, { kind: args.kind, resolveDir: mcpRoot, pluginData: { fromMcp: true } });
      return resolved.errors.length ? { errors: resolved.errors } : { path: resolved.path, external: resolved.external };
    });
  },
};

fs.mkdirSync(outDir, { recursive: true });

for (const [id, site] of Object.entries(SITES)) {
  const siteDir = path.join(repoRoot, site.root);
  const contents = Object.entries(site.modules)
    .map(([name, file]) => `export * as ${name} from ${JSON.stringify(path.join(siteDir, file))};`)
    .join("\n");

  const result = await build({
    stdin: { contents, resolveDir: mcpRoot, sourcefile: `${id}-rules-entry.js`, loader: "js" },
    bundle: true,
    platform: "node",
    format: "esm",
    target: "node22",
    outfile: path.join(outDir, `${id}-rules.mjs`),
    plugins: [resolvePackagesFromMcp],
    metafile: true,
    logLevel: "warning",
    banner: {
      js: [
        `// Generated by scripts/gen-rules.mjs from ${site.root}/lib. Do not edit.`,
        // Bundled CommonJS dependencies (ajv) call require(); give the ESM bundle one.
        `import { createRequire as __rulesCreateRequire } from "node:module";`,
        `const require = __rulesCreateRequire(import.meta.url);`,
      ].join("\n"),
    },
  });

  const files = {};
  for (const input of Object.keys(result.metafile.inputs)) {
    const abs = path.resolve(mcpRoot, input);
    const rel = path.relative(repoRoot, abs).split(path.sep).join("/");
    if (!rel.startsWith(`${site.root}/`)) continue;
    if (rel.includes("/node_modules/")) throw new Error(`${rel}: packages must resolve from mcp/node_modules`);
    files[rel] = gitBlobSha(fs.readFileSync(abs));
  }
  fs.writeFileSync(path.join(outDir, `${id}-rules.manifest.json`), JSON.stringify({ site: site.root, files }, null, 2) + "\n");

  const decl = Object.keys(site.modules)
    .map((name) => `export declare const ${name}: any;`)
    .join("\n");
  fs.writeFileSync(path.join(outDir, `${id}-rules.d.mts`), `// Generated. Typed by src/sites/types.ts (SiteRules).\n${decl}\n`);
  console.log(`rules: ${id} (${Object.keys(files).length} site files)`);
}
